apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: ecommerce-uat
  labels:
    app: product-service
    environment: uat
    app.kubernetes.io/name: product-service
    app.kubernetes.io/part-of: ecommerce-platform
  annotations:
    service.kubernetes.io/active-version: "blue"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
spec:
  selector:
    app: product-service
    version: blue
    environment: uat
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
