apiVersion: v1
kind: Service
metadata:
  name: product-service-blue
  namespace: ecommerce-uat
  labels:
    app: product-service
    version: blue
    environment: uat
    app.kubernetes.io/name: product-service
    app.kubernetes.io/part-of: ecommerce-platform
spec:
  selector:
    app: product-service
    version: blue
    environment: uat
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
