apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-blue
  labels:
    app: api-gateway
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
      version: blue
  template:
    metadata:
      labels:
        app: api-gateway
        version: blue
    spec:
      containers:
        - name: api-gateway
          image: ${ECR_REPOSITORY}/api-gateway:${VERSION}
          ports:
            - containerPort: 8080
          env:
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: product_service_url
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: order_service_url
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: user_service_url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secrets
                  key: jwt_secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
