apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-blue.yaml
  - deployment-green.yaml
  - service.yaml
  - service-blue.yaml
  - service-green.yaml
  - ../config/api-gateway-config.yaml
  - ../secrets/api-gateway-secrets.yaml

commonLabels:
  app.kubernetes.io/name: api-gateway
  app.kubernetes.io/part-of: ecommerce-platform