apiVersion: v1
kind: Secret
metadata:
  name: product-service-secrets
type: Opaque
data:
  # These are base64 encoded placeholders - replace with actual values
  db_user: ${DB_USER_BASE64}
  db_password: ${DB_PASSWORD_BASE64}
