apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
type: Opaque
data:
  # These are base64 encoded placeholders - replace with actual values
  db_user: ${DB_USER_BASE64}
  db_password: ${DB_PASSWORD_BASE64}
  jwt_secret: ${JWT_SECRET_BASE64}
