apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - prometheus-rbac.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - alertmanager-deployment.yaml
  - alertmanager-service.yaml
  - alertmanager-config.yaml

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml=prometheus-config.yaml
  - name: grafana-dashboards-provider
    literals:
      - |
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          updateIntervalSeconds: 10
          options:
            path: /var/lib/grafana/dashboards

secretGenerator:
  - name: grafana-admin-credentials
    literals:
      - username=admin
      - password=admin123 # This should be changed in a real environment

commonLabels:
  app.kubernetes.io/part-of: ecommerce-monitoring
  app.kubernetes.io/managed-by: kustomize
