name: Promote to UAT

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Service to promote"
        required: true
        type: choice
        options:
          - product-service
          - order-service
          - user-service
          - api-gateway
      version:
        description: "Version to promote (leave empty to use latest QA version)"
        required: false
        type: string

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get version from version.json
        id: get-version
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            VERSION=$(jq -r '.services."${{ github.event.inputs.service }}".qa' version.json)
            echo "Using latest QA version: $VERSION"
          else
            VERSION="${{ github.event.inputs.version }}"
            echo "Using specified version: $VERSION"
            
            # Verify version exists in QA
            QA_VERSION=$(jq -r '.services."${{ github.event.inputs.service }}".qa' version.json)
            if [ "$VERSION" != "$QA_VERSION" ]; then
              echo "Warning: Specified version $VERSION does not match current QA version $QA_VERSION"
            fi
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Promote version
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: us-west-2
          SERVICE_NAME: ${{ github.event.inputs.service }}
          VERSION: ${{ steps.get-version.outputs.version }}
        run: |
          chmod +x ./ecommerce-infra/github-actions/scripts/version-promotion.sh
          ./ecommerce-infra/github-actions/scripts/version-promotion.sh "$SERVICE_NAME" qa uat

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ecommerce-eks-uat --region us-west-2

      - name: Update Kubernetes manifests
        run: |
          # Update the image tag in the kustomization.yaml file
          cd ecommerce-infra/kubernetes/overlays/uat/${{ github.event.inputs.service }}

          # Use sed to update the newTag value
          sed -i "s/newTag: .*/newTag: ${{ steps.get-version.outputs.version }}/" kustomization.yaml

          # Apply the changes
          kubectl apply -k .

      - name: Commit and push version file update
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add version.json
          git add ecommerce-infra/kubernetes/overlays/uat/${{ github.event.inputs.service }}/kustomization.yaml
          git commit -m "Promote ${{ github.event.inputs.service }} from QA to UAT (version ${{ steps.get-version.outputs.version }})"
          git push

      - name: Run smoke tests
        run: |
          echo "Running smoke tests for ${{ github.event.inputs.service }} in UAT environment..."
          # Add smoke test commands here
          sleep 10
          echo "Smoke tests passed!"

      - name: Notify on success
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "✅ Successfully promoted ${{ github.event.inputs.service }} version ${{ steps.get-version.outputs.version }} to UAT environment"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify on failure
        if: failure()
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "❌ Failed to promote ${{ github.event.inputs.service }} to UAT environment"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
