apiVersion: v1
kind: Service
metadata:
  name: user-service
  annotations:
    service.kubernetes.io/active-version: "blue"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
spec:
  selector:
    app: user-service
    version: blue
    environment: prod
