apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-blue.yaml
  - deployment-green.yaml
  - service.yaml
  - service-blue.yaml
  - service-green.yaml
  - ../config/product-service-config.yaml
  - ../secrets/product-service-secrets.yaml

commonLabels:
  app.kubernetes.io/name: product-service
  app.kubernetes.io/part-of: ecommerce-platform
