apiVersion: v1
kind: Service
metadata:
  name: product-service
  annotations:
    service.kubernetes.io/active-version: "blue" # This annotation tracks which version is active
spec:
  selector:
    app: product-service
    version: blue # This will be switched between blue and green
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
