apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - product-service
  - order-service
  - user-service
  - api-gateway
  - monitoring

commonLabels:
  environment: qa
  app.kubernetes.io/part-of: ecommerce
  app.kubernetes.io/managed-by: kustomize

namespace: ecommerce-qa
