apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: ecommerce-qa
  labels:
    app: product-service
    environment: qa
    app.kubernetes.io/name: product-service
    app.kubernetes.io/part-of: ecommerce-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
      environment: qa
  template:
    metadata:
      labels:
        app: product-service
        environment: qa
        app.kubernetes.io/name: product-service
        app.kubernetes.io/part-of: ecommerce-platform
    spec:
      containers:
        - name: product-service
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          env:
            - name: NODE_ENV
              value: "qa"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: db_host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: db_port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: db_name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: product-service-secrets
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-service-secrets
                  key: db_password
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
      volumes:
        - name: nginx-config
          configMap:
            name: product-nginx-config
