apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-blue
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: product-service
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          env:
            - name: NODE_ENV
              value: "qa"
            - name: LOG_LEVEL
              value: "info"
            - name: ENABLE_INVENTORY_CHECK
              value: "true"
            - name: ENABLE_RECOMMENDATIONS
              value: "false"
            - name: ENABLE_CACHING
              value: "true"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-green
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: product-service
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          env:
            - name: NODE_ENV
              value: "qa"
            - name: LOG_LEVEL
              value: "info"
            - name: ENABLE_INVENTORY_CHECK
              value: "true"
            - name: ENABLE_RECOMMENDATIONS
              value: "false"
            - name: ENABLE_CACHING
              value: "true"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
