apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-qa

resources:
  - deployment.yaml
  - service.yaml
  - nginx-config.yaml

commonLabels:
  environment: qa
  app.kubernetes.io/name: product-service
  app.kubernetes.io/part-of: ecommerce-platform
