apiVersion: v1
kind: Service
metadata:
  name: product-service-blue
  namespace: ecommerce-qa
  labels:
    app: product-service
    version: blue
    environment: qa
    app.kubernetes.io/name: product-service
    app.kubernetes.io/part-of: ecommerce-platform
spec:
  selector:
    app: product-service
    version: blue
    environment: qa
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
