apiVersion: v1
kind: Service
metadata:
  name: product-service-blue
  namespace: ecommerce-qa
spec:
  selector:
    app: product-service
    version: blue
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
