apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: ecommerce-qa
  annotations:
    service.kubernetes.io/active-version: "blue"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
spec:
  selector:
    app: product-service
    version: blue
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
