apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ecommerce-qa
  labels:
    app: order-service
    environment: qa
    app.kubernetes.io/name: order-service
    app.kubernetes.io/part-of: ecommerce-platform
  annotations:
    service.kubernetes.io/active-version: "blue"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
spec:
  selector:
    app: order-service
    version: blue
    environment: qa
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
