apiVersion: v1
kind: Service
metadata:
  name: order-service-blue
  namespace: ecommerce-qa
  labels:
    app: order-service
    version: blue
    environment: qa
    app.kubernetes.io/name: order-service
    app.kubernetes.io/part-of: ecommerce-platform
spec:
  selector:
    app: order-service
    version: blue
    environment: qa
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
