apiVersion: v1
kind: Service
metadata:
  name: order-service-green
  namespace: ecommerce-qa
  labels:
    app: order-service
    version: green
    environment: qa
    app.kubernetes.io/name: order-service
    app.kubernetes.io/part-of: ecommerce-platform
spec:
  selector:
    app: order-service
    version: green
    environment: qa
  ports:
    - port: 80
      targetPort: 8082
  type: ClusterIP
