---
# EC2 Configuration Playbook
# This playbook configures EC2 instances for the EKS cluster

- name: Configure EC2 instances for EKS
  hosts: eks_nodes
  become: true
  gather_facts: true

  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest
        update_only: yes

    - name: Install required packages
      yum:
        name:
          - docker
          - python3
          - python3-pip
          - git
          - jq
          - wget
          - unzip
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Install AWS CLI
      pip:
        name: awscli
        executable: pip3
        state: latest

    - name: Install kubectl
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.27.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: "0755"

    - name: Configure kubectl for EKS cluster
      shell: |
        aws eks update-kubeconfig --name {{ kubernetes_cluster }} --region {{ aws_region }} --kubeconfig {{ kube_config_path }}
      args:
        creates: "{{ kube_config_path }}"
      environment:
        AWS_DEFAULT_REGION: "{{ aws_region }}"

    - name: Create symbolic link for kubectl config
      file:
        src: "{{ kube_config_path }}"
        dest: /home/ec2-user/.kube/config
        state: link
        force: yes

    - name: Set correct permissions for kubectl config
      file:
        path: "{{ kube_config_path }}"
        owner: ec2-user
        group: ec2-user
        mode: "0600"
