apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-green
  namespace: ecommerce-qa
  labels:
    app: user-service
    version: green
    environment: qa
    app.kubernetes.io/name: user-service
    app.kubernetes.io/part-of: ecommerce-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
      version: green
      environment: qa
  template:
    metadata:
      labels:
        app: user-service
        version: green
        environment: qa
        app.kubernetes.io/name: user-service
        app.kubernetes.io/part-of: ecommerce-platform
    spec:
      containers:
        - name: user-service
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/ecommerce-qa/user-service:${VERSION}
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "qa"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: db_host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: db_port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: db_name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-service-secrets
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-service-secrets
                  key: db_password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-service-secrets
                  key: jwt_secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
