apiVersion: v1
kind: Service
metadata:
  name: user-service-green
  namespace: ecommerce-qa
  labels:
    app: user-service
    version: green
    environment: qa
    app.kubernetes.io/name: user-service
    app.kubernetes.io/part-of: ecommerce-platform
spec:
  selector:
    app: user-service
    version: green
    environment: qa
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
