apiVersion: v1
kind: Service
metadata:
  name: product-service-green
  namespace: ecommerce-prod
  labels:
    app: product-service
    version: green
    environment: prod
    app.kubernetes.io/name: product-service
    app.kubernetes.io/part-of: ecommerce-platform
spec:
  selector:
    app: product-service
    version: green
    environment: prod
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
