apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
data:
  db_host: "order-db.${ENVIRONMENT}.svc.cluster.local"
  db_port: "3306"
  db_name: "ecommerce_orders"
  product_service_url: "http://product-service.${ENVIRONMENT}.svc.cluster.local"
  user_service_url: "http://user-service.${ENVIRONMENT}.svc.cluster.local"
