apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uat

resources:
  - ../../../base/user-service

commonLabels:
  environment: uat

images:
  - name: ${ECR_REPOSITORY}/user-service
    newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/uat-user-service
    newTag: ${VERSION}

configMapGenerator:
  - name: user-service-config
    literals:
      - db_host=${DB_HOST}
      - db_port=3306
      - db_name=ecommerce_users
      - log_level=info

secretGenerator:
  - name: user-service-secrets
    literals:
      - db_username=${DB_USERNAME}
      - db_password=${DB_PASSWORD}
      - jwt_secret=${JWT_SECRET}

patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml
