apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-green
  namespace: ecommerce-qa
  labels:
    app: api-gateway
    version: green
    environment: qa
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: ecommerce-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
      version: green
      environment: qa
  template:
    metadata:
      labels:
        app: api-gateway
        version: green
        environment: qa
        app.kubernetes.io/name: api-gateway
        app.kubernetes.io/part-of: ecommerce-platform
    spec:
      containers:
        - name: api-gateway
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          env:
            - name: NODE_ENV
              value: "qa"
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: product_service_url
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: order_service_url
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: user_service_url
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: log_level
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secrets
                  key: jwt_secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
