apiVersion: v1
kind: Service
metadata:
  name: api-gateway-blue
  namespace: ecommerce-qa
  labels:
    app: api-gateway
    version: blue
    environment: qa
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: ecommerce-platform
spec:
  selector:
    app: api-gateway
    version: blue
    environment: qa
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
