apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: ecommerce-qa
  labels:
    app: api-gateway
    environment: qa
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: ecommerce-platform
  annotations:
    service.kubernetes.io/active-version: "blue"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "80"
spec:
  selector:
    app: api-gateway
    version: blue
    environment: qa
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
